# Scheduler intervals in seconds, recommended to leave as default values.
# Setting to 0 disables the scheduler from running.
# Only change if you know what you are doing!
scheduler:
  expiresCheck: 5
  playerBans: 5
  playerMutes: 5
  playerWarnings: 5
  ipBans: 5
  ipRangeBans: 5
  rollbacks: 30
  nameBans: 5
  externalPlayerBans: 5
  externalPlayerMutes: 5
  externalPlayerNotes: 5
  externalIpBans: 5
  saveLastChecked: 60
lastChecked:
  externalPlayerNotes: 0
  playerMutes: 1685275616
  ipRangeBans: 1685275616
  expiresCheck: 1685275616
  nameBans: 1685275616
  externalPlayerMutes: 0
  rollbacks: 1685275604
  playerBans: 1685275617
  externalPlayerBans: 0
  externalIpBans: 0
  playerWarnings: 1685275617
  ipBans: 1685275617
